#pragma once

#ifndef AUDIO_ID_H
#define AUDIO_ID_H
enum AUDIO_ID {				// 定義各種音效的編號
	AUDIO_JELLY, AUDIO_STAGE,
	AUDIO_NEG_SWAP, AUDIO_SWAP,
	AUDIO_SUPER_CREATE, AUDIO_LINE_CREATE, AUDIO_PACK_CREATE, AUDIO_POWER_ALL,
	AUDIO_SQUARE_REMOVE1, AUDIO_SQUARE_REMOVE2, AUDIO_LINE_BLAST, AUDIO_SUPER_REMOVE,
	AUDIO_CANDY_LAND1, AUDIO_CANDY_LAND2, AUDIO_CANDY_LAND3, AUDIO_CANDY_LAND4,
	AUDIO_COMBO1, AUDIO_COMBO2, AUDIO_COMBO3, AUDIO_COMBO4, AUDIO_COMBO5, AUDIO_COMBO6,
	AUDIO_COMBO7, AUDIO_COMBO8, AUDIO_COMBO9, AUDIO_COMBO10, AUDIO_COMBO11, AUDIO_COMBO12,
	AUDIO_SWEET, AUDIO_TASTY, AUDIO_DELICIOUS, AUDIO_DIVINE, AUDIO_SUGAR_CRUSH,
	AUDIO_LEVEL_FAIL, AUDIO_LEVEL_COMPLETE, AUDIO_STATE_FAIL, AUDIO_STATE_COMPLETE,
	AUDIO_BTN_CLICK, AUDIO_BTN_RELEASE
};
#endif