//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         101
#define IDB_STAGE_BUTTON_BLUE           102
#define IDB_STAGE_BUTTON_GREY           103
#define IDB_STAGE_BUTTON_RED            104
#define IDB_STAGE_BUTTON_YELLOW         105
#define IDB_STAGE_BUTTON_GREEN          106
#define IDB_TOFFEE_1                    107
#define IDB_TOFFEE_2                    108
#define IDB_TOFFEE_3                    109
#define IDB_TOFFEE_4                    110
#define IDB_TOFFEE_5                    111
#define IDB_TOFFEE_6                    112
#define IDB1_0                          113
#define IDB1_1                          114
#define IDB1_2                          115
#define IDB1_3                          116
#define IDB1_4                          117
#define IDB1_5                          118
#define IDB1_6                          119
#define IDB1_7                          120
#define IDB1_8                          121
#define IDB1_9                          122
#define IDR_MAINFRAME                   123
#define IDR_GAMETYPE                    124
#define IDB_RACKET                      125
#define IDB_BITMAP1                     126
#define IDB_0                           131
#define IDB_1                           132
#define IDB_2                           133
#define IDB_3                           134
#define IDB_4                           135
#define IDB_5                           136
#define IDB_6                           137
#define IDB_7                           138
#define IDB_8                           139
#define IDB_9                           140
#define IDB_MINUS                       141
#define IDB_CONTINUE                    142
#define IDC_GAMECURSOR                  143
#define IDB_LOADING                     144
#define IDB_LOGIN_LOADING               145
#define IDB_INGAME_LOADING              146
#define IDB_RED_NOR                     147
#define IDB_RED_HOR                     148
#define IDB_RED_HOR_C                   149
#define IDB_RED_NOR_C                   150
#define IDB_RED_PAC                     151
#define IDB_RED_PAC_C                   152
#define IDB_RED_VER                     153
#define IDB_RED_VER_C                   154
#define IDB_BLU_HOR                     155
#define IDB_GRE_HOR                     156
#define IDB_PUR_VER_C                   157
#define IDB_PUR_PAC                     158
#define IDB_PUR_PAC_C                   159
#define IDB_SUPER_C                     160
#define IDB_ORG_PAC                     161
#define IDB_ORG_HOR_C                   162
#define IDB_PUR_NOR_C                   163
#define IDB_ORG_VER                     164
#define IDB_ORG_VER_C                   165
#define IDB_PUR_HOR                     166
#define IDB_PUR_VER                     167
#define IDB_GRE_PAC_C                   168
#define IDB_GRE_VER                     169
#define IDB_PUR_NOR                     170
#define IDB_GRE_PAC                     171
#define IDB_GRE_NOR                     172
#define IDB_ORG_PAC_C                   173
#define IDB_PUR_HOR_C                   174
#define IDB_ORG_HOR                     175
#define IDB_BLU_VER_C                   176
#define IDB_ORG_NOR                     177
#define IDB_BLU_PAC_C                   178
#define IDB_ORG_NOR_C                   179
#define IDB_GRE_HOR_C                   180
#define IDB_GRE_VER_C                   181
#define IDB_SUPER                       182
#define IDB_BLU_VER                     183
#define IDB_GRE_NOR_C                   184
#define IDB_BLU_PAC                     185
#define IDB_BLU_HOR_C                   186
#define IDB_BLU_NOR_C                   187
#define IDB_BLU_NOR                     188
#define IDB_CONTAINER                   189
#define IDB_YEL_HOR                     190
#define IDB_YEL_HOR_C                   191
#define IDB_YEL_NOR                     192
#define IDB_YEL_NOR_C                   193
#define IDB_YEL_PAC                     194
#define IDB_YEL_VER                     195
#define IDB_YEL_VER_C                   196
#define IDB_YEL_PAC_C                   197
#define IDB_BLACK_BAR                   198
#define IDB_TIFFY_0                     199
#define IDB_TIFFY_1                     200
#define IDB_NOR_EXPL1                   201
#define IDB_NOR_EXPL4                   202
#define IDB_NOR_EXPL3                   203
#define IDB_NOR_EXPL2                   204
#define IDB_NOR_EXPL9                   205
#define IDB_NOR_EXPL6                   206
#define IDB_NOR_EXPL8                   207
#define IDB_NOR_EXPL5                   208
#define IDB_NOR_EXPL7                   209
#define IDB_NOR_EXPL10                  210
#define IDB_YEL_EXPL9                   211
#define IDB_RED_EXPL2                   212
#define IDB_YEL_EXPL6                   213
#define IDB_YEL_EXPL3                   214
#define IDB_YEL_EXPL7                   215
#define IDB_YEL_EXPL5                   216
#define IDB_YEL_EXPL8                   217
#define IDB_YEL_EXPL4                   218
#define IDB_YEL_EXPL2                   219
#define IDB_YEL_EXPL10                  220
#define IDB_RED_EXPL9                   221
#define IDB_YEL_EXPL1                   222
#define IDB_RED_EXPL7                   223
#define IDB_PUR_EXPL2                   224
#define IDB_BLU_EXPL1                   225
#define IDB_BLU_EXPL9                   226
#define IDB_BLU_EXPL6                   227
#define IDB_RED_EXPL5                   228
#define IDB_BLU_EXPL7                   229
#define IDB_RED_EXPL8                   230
#define IDB_GRE_EXPL10                  231
#define IDB_BLU_EXPL5                   232
#define IDB_RED_EXPL6                   233
#define IDB_GRE_EXPL4                   234
#define IDB_ORG_EXPL1                   235
#define IDB_GRE_EXPL3                   236
#define IDB_GRE_EXPL8                   237
#define IDB_PUR_EXPL9                   238
#define IDB_ORG_EXPL2                   239
#define IDB_ORG_EXPL4                   240
#define IDB_GRE_EXPL7                   241
#define IDB_RED_EXPL4                   242
#define IDB_PUR_EXPL7                   243
#define IDB_PUR_EXPL6                   244
#define IDB_PUR_EXPL3                   245
#define IDB_RED_EXPL10                  246
#define IDB_PUR_EXPL8                   247
#define IDB_PUR_EXPL1                   248
#define IDB_RED_EXPL3                   249
#define IDB_RED_EXPL1                   250
#define IDB_GRE_EXPL2                   251
#define IDB_GRE_EXPL1                   252
#define IDB_ORG_EXPL7                   253
#define IDB_ORG_EXPL10                  254
#define IDB_GRE_EXPL5                   255
#define IDB_ORG_EXPL6                   256
#define IDB_GRE_EXPL6                   257
#define IDB_ORG_EXPL5                   258
#define IDB_ORG_EXPL3                   259
#define IDB_PUR_EXPL4                   260
#define IDB_PUR_EXPL10                  261
#define IDB_GRE_EXPL9                   262
#define IDB_ORG_EXPL9                   263
#define IDB_PUR_EXPL5                   264
#define IDB_BLU_EXPL8                   265
#define IDB_ORG_EXPL8                   266
#define IDB_BLU_EXPL4                   267
#define IDB_BLU_EXPL3                   268
#define IDB_BLU_EXPL2                   269
#define IDB_BLU_EXPL10                  270
#define IDB_RED_SHAT1                   271
#define IDB_RED_SHAT2                   272
#define IDB_RED_SHAT3                   273
#define IDB_RED_SHAT4                   274
#define IDB_RED_SHAT5                   275
#define IDB_RED_SHAT6                   276
#define IDB_RED_SHAT7                   277
#define IDB_RED_SHAT8                   278
#define IDB_RED_SHAT9                   279
#define IDB_RED_SHAT10                  280
#define IDB_RED_SHAT11                  281
#define IDB_RED_SHAT12                  282
#define IDB_RED_SHAT13                  283
#define IDB_RED_SHAT14                  284
#define IDB_RED_SHAT15                  285
#define IDB_ORG_SHAT1                   286
#define IDB_ORG_SHAT2                   287
#define IDB_ORG_SHAT3                   288
#define IDB_ORG_SHAT4                   289
#define IDB_ORG_SHAT5                   290
#define IDB_ORG_SHAT6                   291
#define IDB_ORG_SHAT7                   292
#define IDB_ORG_SHAT8                   293
#define IDB_ORG_SHAT9                   294
#define IDB_ORG_SHAT10                  295
#define IDB_ORG_SHAT11                  296
#define IDB_ORG_SHAT12                  297
#define IDB_ORG_SHAT13                  298
#define IDB_ORG_SHAT14                  299
#define IDB_ORG_SHAT15                  300
#define IDB_YEL_SHAT1                   301
#define IDB_YEL_SHAT2                   302
#define IDB_YEL_SHAT3                   303
#define IDB_YEL_SHAT4                   304
#define IDB_YEL_SHAT5                   305
#define IDB_YEL_SHAT6                   306
#define IDB_YEL_SHAT7                   307
#define IDB_YEL_SHAT8                   308
#define IDB_YEL_SHAT9                   309
#define IDB_YEL_SHAT10                  310
#define IDB_YEL_SHAT11                  311
#define IDB_YEL_SHAT12                  312
#define IDB_YEL_SHAT13                  313
#define IDB_YEL_SHAT14                  314
#define IDB_YEL_SHAT15                  315
#define IDB_GRE_SHAT1                   316
#define IDB_GRE_SHAT2                   317
#define IDB_GRE_SHAT3                   318
#define IDB_GRE_SHAT4                   319
#define IDB_GRE_SHAT5                   320
#define IDB_GRE_SHAT6                   321
#define IDB_GRE_SHAT7                   322
#define IDB_GRE_SHAT8                   323
#define IDB_GRE_SHAT9                   324
#define IDB_GRE_SHAT10                  325
#define IDB_GRE_SHAT11                  326
#define IDB_GRE_SHAT12                  327
#define IDB_GRE_SHAT13                  328
#define IDB_GRE_SHAT14                  329
#define IDB_GRE_SHAT15                  330
#define IDB_BLU_SHAT1                   331
#define IDB_BLU_SHAT2                   332
#define IDB_BLU_SHAT3                   333
#define IDB_BLU_SHAT4                   334
#define IDB_BLU_SHAT5                   335
#define IDB_BLU_SHAT6                   336
#define IDB_BLU_SHAT7                   337
#define IDB_BLU_SHAT8                   338
#define IDB_BLU_SHAT9                   339
#define IDB_BLU_SHAT10                  340
#define IDB_BLU_SHAT11                  341
#define IDB_BLU_SHAT12                  342
#define IDB_BLU_SHAT13                  343
#define IDB_BLU_SHAT14                  344
#define IDB_BLU_SHAT15                  345
#define IDB_PUR_SHAT1                   346
#define IDB_PUR_SHAT2                   347
#define IDB_PUR_SHAT3                   348
#define IDB_PUR_SHAT4                   349
#define IDB_PUR_SHAT5                   350
#define IDB_PUR_SHAT6                   351
#define IDB_PUR_SHAT7                   352
#define IDB_PUR_SHAT8                   353
#define IDB_PUR_SHAT9                   354
#define IDB_PUR_SHAT10                  355
#define IDB_PUR_SHAT11                  356
#define IDB_PUR_SHAT12                  357
#define IDB_PUR_SHAT13                  358
#define IDB_PUR_SHAT14                  359
#define IDB_PUR_SHAT15                  360
#define IDB_TIFFY_2                     361
#define IDB_TIFFY_3                     362
#define IDB_TIFFY_4                     363
#define IDB_TIFFY_5                     364
#define IDB_TIFFY_6                     365
#define IDB_TIFFY_7                     366
#define IDB_TIFFY_8                     367
#define IDB_TIFFY_9                     368
#define IDB_PLAYBUTTON_1                369
#define IDB_PLAYBUTTON_2                370
#define IDB_PLAYBUTTON_3                371
#define IDB_PLAYBUTTON_4                372
#define IDB_PLAYBUTTON_5                373
#define IDB_PLAYBUTTON_6                374
#define IDB_PLAYBUTTON_7                375
#define IDB_PLAYBUTTON_8                376
#define IDB_PLAYBUTTON_9                377
#define IDB_PLAYBUTTON_10               378
#define IDB_PLAYBUTTON_11               379
#define IDB_PLAYBUTTON_12               380
#define IDB_RED_VEXPL1                  381
#define IDB_RED_VEXPL2                  382
#define IDB_RED_VEXPL3                  383
#define IDB_RED_VEXPL4                  384
#define IDB_RED_VEXPL5                  385
#define IDB_RED_VEXPL6                  386
#define IDB_RED_VEXPL7                  387
#define IDB_RED_VEXPL8                  388
#define IDB_RED_VEXPL9                  389
#define IDB_RED_VEXPL10                 390
#define IDB_RED_VEXPL11                 391
#define IDB_RED_VEXPL12                 392
#define IDB_RED_VEXPL13                 393
#define IDB_RED_VEXPL14                 394
#define IDB_RED_VEXPL15                 395
#define IDB_RED_VEXPL16                 396
#define IDB_RED_VEXPL17                 397
#define IDB_RED_VEXPL18                 398
#define IDB_RED_VEXPL19                 399
#define IDB_RED_VEXPL20                 400
#define IDB_RED_VEXPL21                 401
#define IDB_RED_VEXPL22                 402
#define IDB_RED_VEXPL23                 403
#define IDB_RED_VEXPL24                 404
#define IDB_RED_VEXPL25                 405
#define IDB_RED_VEXPL26                 406
#define IDB_RED_VEXPL27                 407
#define IDB_RED_VEXPL28                 408
#define IDB_RED_VEXPL29                 409
#define IDB_RED_VEXPL30                 410
#define IDB_RED_HEXPL1                  411
#define IDB_RED_HEXPL2                  412
#define IDB_RED_HEXPL3                  413
#define IDB_RED_HEXPL4                  414
#define IDB_RED_HEXPL5                  415
#define IDB_RED_HEXPL6                  416
#define IDB_RED_HEXPL7                  417
#define IDB_RED_HEXPL8                  418
#define IDB_RED_HEXPL9                  419
#define IDB_RED_HEXPL10                 420
#define IDB_RED_HEXPL11                 421
#define IDB_RED_HEXPL12                 422
#define IDB_RED_HEXPL13                 423
#define IDB_RED_HEXPL14                 424
#define IDB_RED_HEXPL15                 425
#define IDB_RED_HEXPL16                 426
#define IDB_RED_HEXPL17                 427
#define IDB_RED_HEXPL18                 428
#define IDB_RED_HEXPL19                 429
#define IDB_RED_HEXPL20                 430
#define IDB_RED_HEXPL21                 431
#define IDB_RED_HEXPL22                 432
#define IDB_RED_HEXPL23                 433
#define IDB_RED_HEXPL24                 434
#define IDB_RED_HEXPL25                 435
#define IDB_RED_HEXPL26                 436
#define IDB_RED_HEXPL27                 437
#define IDB_RED_HEXPL28                 438
#define IDB_RED_HEXPL29                 439
#define IDB_RED_HEXPL30                 440
#define IDB_ORG_VEXPL1                  441
#define IDB_ORG_VEXPL2                  442
#define IDB_ORG_VEXPL3                  443
#define IDB_ORG_VEXPL4                  444
#define IDB_ORG_VEXPL5                  445
#define IDB_ORG_VEXPL6                  446
#define IDB_ORG_VEXPL7                  447
#define IDB_ORG_VEXPL8                  448
#define IDB_ORG_VEXPL9                  449
#define IDB_ORG_VEXPL10                 450
#define IDB_ORG_VEXPL11                 451
#define IDB_ORG_VEXPL12                 452
#define IDB_ORG_VEXPL13                 453
#define IDB_ORG_VEXPL14                 454
#define IDB_ORG_VEXPL15                 455
#define IDB_ORG_VEXPL16                 456
#define IDB_ORG_VEXPL17                 457
#define IDB_ORG_VEXPL18                 458
#define IDB_ORG_VEXPL19                 459
#define IDB_ORG_VEXPL20                 460
#define IDB_ORG_VEXPL21                 461
#define IDB_ORG_VEXPL22                 462
#define IDB_ORG_VEXPL23                 463
#define IDB_ORG_VEXPL24                 464
#define IDB_ORG_VEXPL25                 465
#define IDB_ORG_VEXPL26                 466
#define IDB_ORG_VEXPL27                 467
#define IDB_ORG_VEXPL28                 468
#define IDB_ORG_VEXPL29                 469
#define IDB_ORG_VEXPL30                 470
#define IDB_ORG_HEXPL1                  471
#define IDB_ORG_HEXPL2                  472
#define IDB_ORG_HEXPL3                  473
#define IDB_ORG_HEXPL4                  474
#define IDB_ORG_HEXPL5                  475
#define IDB_ORG_HEXPL6                  476
#define IDB_ORG_HEXPL7                  477
#define IDB_ORG_HEXPL8                  478
#define IDB_ORG_HEXPL9                  479
#define IDB_ORG_HEXPL10                 480
#define IDB_ORG_HEXPL11                 481
#define IDB_ORG_HEXPL12                 482
#define IDB_ORG_HEXPL13                 483
#define IDB_ORG_HEXPL14                 484
#define IDB_ORG_HEXPL15                 485
#define IDB_ORG_HEXPL16                 486
#define IDB_ORG_HEXPL17                 487
#define IDB_ORG_HEXPL18                 488
#define IDB_ORG_HEXPL19                 489
#define IDB_ORG_HEXPL20                 490
#define IDB_ORG_HEXPL21                 491
#define IDB_ORG_HEXPL22                 492
#define IDB_ORG_HEXPL23                 493
#define IDB_ORG_HEXPL24                 494
#define IDB_ORG_HEXPL25                 495
#define IDB_ORG_HEXPL26                 496
#define IDB_ORG_HEXPL27                 497
#define IDB_ORG_HEXPL28                 498
#define IDB_ORG_HEXPL29                 499
#define IDB_ORG_HEXPL30                 500
#define IDB_YEL_VEXPL1                  501
#define IDB_YEL_VEXPL2                  502
#define IDB_YEL_VEXPL3                  503
#define IDB_YEL_VEXPL4                  504
#define IDB_YEL_VEXPL5                  505
#define IDB_YEL_VEXPL6                  506
#define IDB_YEL_VEXPL7                  507
#define IDB_YEL_VEXPL8                  508
#define IDB_YEL_VEXPL9                  509
#define IDB_YEL_VEXPL10                 510
#define IDB_YEL_VEXPL11                 511
#define IDB_YEL_VEXPL12                 512
#define IDB_YEL_VEXPL13                 513
#define IDB_YEL_VEXPL14                 514
#define IDB_YEL_VEXPL15                 515
#define IDB_YEL_VEXPL16                 516
#define IDB_YEL_VEXPL17                 517
#define IDB_YEL_VEXPL18                 518
#define IDB_YEL_VEXPL19                 519
#define IDB_YEL_VEXPL20                 520
#define IDB_YEL_VEXPL21                 521
#define IDB_YEL_VEXPL22                 522
#define IDB_YEL_VEXPL23                 523
#define IDB_YEL_VEXPL24                 524
#define IDB_YEL_VEXPL25                 525
#define IDB_YEL_VEXPL26                 526
#define IDB_YEL_VEXPL27                 527
#define IDB_YEL_VEXPL28                 528
#define IDB_YEL_VEXPL29                 529
#define IDB_YEL_VEXPL30                 530
#define IDB_YEL_HEXPL1                  531
#define IDB_YEL_HEXPL2                  532
#define IDB_YEL_HEXPL3                  533
#define IDB_YEL_HEXPL4                  534
#define IDB_YEL_HEXPL5                  535
#define IDB_YEL_HEXPL6                  536
#define IDB_YEL_HEXPL7                  537
#define IDB_YEL_HEXPL8                  538
#define IDB_YEL_HEXPL9                  539
#define IDB_YEL_HEXPL10                 540
#define IDB_YEL_HEXPL11                 541
#define IDB_YEL_HEXPL12                 542
#define IDB_YEL_HEXPL13                 543
#define IDB_YEL_HEXPL14                 544
#define IDB_YEL_HEXPL15                 545
#define IDB_YEL_HEXPL16                 546
#define IDB_YEL_HEXPL17                 547
#define IDB_YEL_HEXPL18                 548
#define IDB_YEL_HEXPL19                 549
#define IDB_YEL_HEXPL20                 550
#define IDB_YEL_HEXPL21                 551
#define IDB_YEL_HEXPL22                 552
#define IDB_YEL_HEXPL23                 553
#define IDB_YEL_HEXPL24                 554
#define IDB_YEL_HEXPL25                 555
#define IDB_YEL_HEXPL26                 556
#define IDB_YEL_HEXPL27                 557
#define IDB_YEL_HEXPL28                 558
#define IDB_YEL_HEXPL29                 559
#define IDB_YEL_HEXPL30                 560
#define IDB_GRE_VEXPL1                  561
#define IDB_GRE_VEXPL2                  562
#define IDB_GRE_VEXPL3                  563
#define IDB_GRE_VEXPL4                  564
#define IDB_GRE_VEXPL5                  565
#define IDB_GRE_VEXPL6                  566
#define IDB_GRE_VEXPL7                  567
#define IDB_GRE_VEXPL8                  568
#define IDB_GRE_VEXPL9                  569
#define IDB_GRE_VEXPL10                 570
#define IDB_GRE_VEXPL11                 571
#define IDB_GRE_VEXPL12                 572
#define IDB_GRE_VEXPL13                 573
#define IDB_GRE_VEXPL14                 574
#define IDB_GRE_VEXPL15                 575
#define IDB_GRE_VEXPL16                 576
#define IDB_GRE_VEXPL17                 577
#define IDB_GRE_VEXPL18                 578
#define IDB_GRE_VEXPL19                 579
#define IDB_GRE_VEXPL20                 580
#define IDB_GRE_VEXPL21                 581
#define IDB_GRE_VEXPL22                 582
#define IDB_GRE_VEXPL23                 583
#define IDB_GRE_VEXPL24                 584
#define IDB_GRE_VEXPL25                 585
#define IDB_GRE_VEXPL26                 586
#define IDB_GRE_VEXPL27                 587
#define IDB_GRE_VEXPL28                 588
#define IDB_GRE_VEXPL29                 589
#define IDB_GRE_VEXPL30                 590
#define IDB_GRE_HEXPL1                  591
#define IDB_GRE_HEXPL2                  592
#define IDB_GRE_HEXPL3                  593
#define IDB_GRE_HEXPL4                  594
#define IDB_GRE_HEXPL5                  595
#define IDB_GRE_HEXPL6                  596
#define IDB_GRE_HEXPL7                  597
#define IDB_GRE_HEXPL8                  598
#define IDB_GRE_HEXPL9                  599
#define IDB_GRE_HEXPL10                 600
#define IDB_GRE_HEXPL11                 601
#define IDB_GRE_HEXPL12                 602
#define IDB_GRE_HEXPL13                 603
#define IDB_GRE_HEXPL14                 604
#define IDB_GRE_HEXPL15                 605
#define IDB_GRE_HEXPL16                 606
#define IDB_GRE_HEXPL17                 607
#define IDB_GRE_HEXPL18                 608
#define IDB_GRE_HEXPL19                 609
#define IDB_GRE_HEXPL20                 610
#define IDB_GRE_HEXPL21                 611
#define IDB_GRE_HEXPL22                 612
#define IDB_GRE_HEXPL23                 613
#define IDB_GRE_HEXPL24                 614
#define IDB_GRE_HEXPL25                 615
#define IDB_GRE_HEXPL26                 616
#define IDB_GRE_HEXPL27                 617
#define IDB_GRE_HEXPL28                 618
#define IDB_GRE_HEXPL29                 619
#define IDB_GRE_HEXPL30                 620
#define IDB_BLU_VEXPL1                  621
#define IDB_BLU_VEXPL2                  622
#define IDB_BLU_VEXPL3                  623
#define IDB_BLU_VEXPL4                  624
#define IDB_BLU_VEXPL5                  625
#define IDB_BLU_VEXPL6                  626
#define IDB_BLU_VEXPL7                  627
#define IDB_BLU_VEXPL8                  628
#define IDB_BLU_VEXPL9                  629
#define IDB_BLU_VEXPL10                 630
#define IDB_BLU_VEXPL11                 631
#define IDB_BLU_VEXPL12                 632
#define IDB_BLU_VEXPL13                 633
#define IDB_BLU_VEXPL14                 634
#define IDB_BLU_VEXPL15                 635
#define IDB_BLU_VEXPL16                 636
#define IDB_BLU_VEXPL17                 637
#define IDB_BLU_VEXPL18                 638
#define IDB_BLU_VEXPL19                 639
#define IDB_BLU_VEXPL20                 640
#define IDB_BLU_VEXPL21                 641
#define IDB_BLU_VEXPL22                 642
#define IDB_BLU_VEXPL23                 643
#define IDB_BLU_VEXPL24                 644
#define IDB_BLU_VEXPL25                 645
#define IDB_BLU_VEXPL26                 646
#define IDB_BLU_VEXPL27                 647
#define IDB_BLU_VEXPL28                 648
#define IDB_BLU_VEXPL29                 649
#define IDB_BLU_VEXPL30                 650
#define IDB_BLU_HEXPL1                  651
#define IDB_BLU_HEXPL2                  652
#define IDB_BLU_HEXPL3                  653
#define IDB_BLU_HEXPL4                  654
#define IDB_BLU_HEXPL5                  655
#define IDB_BLU_HEXPL6                  656
#define IDB_BLU_HEXPL7                  657
#define IDB_BLU_HEXPL8                  658
#define IDB_BLU_HEXPL9                  659
#define IDB_BLU_HEXPL10                 660
#define IDB_BLU_HEXPL11                 661
#define IDB_BLU_HEXPL12                 662
#define IDB_BLU_HEXPL13                 663
#define IDB_BLU_HEXPL14                 664
#define IDB_BLU_HEXPL15                 665
#define IDB_BLU_HEXPL16                 666
#define IDB_BLU_HEXPL17                 667
#define IDB_BLU_HEXPL18                 668
#define IDB_BLU_HEXPL19                 669
#define IDB_BLU_HEXPL20                 670
#define IDB_BLU_HEXPL21                 671
#define IDB_BLU_HEXPL22                 672
#define IDB_BLU_HEXPL23                 673
#define IDB_BLU_HEXPL24                 674
#define IDB_BLU_HEXPL25                 675
#define IDB_BLU_HEXPL26                 676
#define IDB_BLU_HEXPL27                 677
#define IDB_BLU_HEXPL28                 678
#define IDB_BLU_HEXPL29                 679
#define IDB_BLU_HEXPL30                 680
#define IDB_PUR_VEXPL1                  681
#define IDB_PUR_VEXPL2                  682
#define IDB_PUR_VEXPL3                  683
#define IDB_PUR_VEXPL4                  684
#define IDB_PUR_VEXPL5                  685
#define IDB_PUR_VEXPL6                  686
#define IDB_PUR_VEXPL7                  687
#define IDB_PUR_VEXPL8                  688
#define IDB_PUR_VEXPL9                  689
#define IDB_PUR_VEXPL10                 690
#define IDB_PUR_VEXPL11                 691
#define IDB_PUR_VEXPL12                 692
#define IDB_PUR_VEXPL13                 693
#define IDB_PUR_VEXPL14                 694
#define IDB_PUR_VEXPL15                 695
#define IDB_PUR_VEXPL16                 696
#define IDB_PUR_VEXPL17                 697
#define IDB_PUR_VEXPL18                 698
#define IDB_PUR_VEXPL19                 699
#define IDB_PUR_VEXPL20                 700
#define IDB_PUR_VEXPL21                 701
#define IDB_PUR_VEXPL22                 702
#define IDB_PUR_VEXPL23                 703
#define IDB_PUR_VEXPL24                 704
#define IDB_PUR_VEXPL25                 705
#define IDB_PUR_VEXPL26                 706
#define IDB_PUR_VEXPL27                 707
#define IDB_PUR_VEXPL28                 708
#define IDB_PUR_VEXPL29                 709
#define IDB_PUR_VEXPL30                 710
#define IDB_PUR_HEXPL1                  711
#define IDB_PUR_HEXPL2                  712
#define IDB_PUR_HEXPL3                  713
#define IDB_PUR_HEXPL4                  714
#define IDB_PUR_HEXPL5                  715
#define IDB_PUR_HEXPL6                  716
#define IDB_PUR_HEXPL7                  717
#define IDB_PUR_HEXPL8                  718
#define IDB_PUR_HEXPL9                  719
#define IDB_PUR_HEXPL10                 720
#define IDB_PUR_HEXPL11                 721
#define IDB_PUR_HEXPL12                 722
#define IDB_PUR_HEXPL13                 723
#define IDB_PUR_HEXPL14                 724
#define IDB_PUR_HEXPL15                 725
#define IDB_PUR_HEXPL16                 726
#define IDB_PUR_HEXPL17                 727
#define IDB_PUR_HEXPL18                 728
#define IDB_PUR_HEXPL19                 729
#define IDB_PUR_HEXPL20                 730
#define IDB_PUR_HEXPL21                 731
#define IDB_PUR_HEXPL22                 732
#define IDB_PUR_HEXPL23                 733
#define IDB_PUR_HEXPL24                 734
#define IDB_PUR_HEXPL25                 735
#define IDB_PUR_HEXPL26                 736
#define IDB_PUR_HEXPL27                 737
#define IDB_PUR_HEXPL28                 738
#define IDB_PUR_HEXPL29                 739
#define IDB_PUR_HEXPL30                 740
#define IDB_CANDY_CRUSH_1               741
#define IDB_CANDY_CRUSH_2               742
#define IDB_CANDY_CRUSH_3               743
#define IDB_CANDY_CRUSH_4               744
#define IDB_CANDY_CRUSH_5               745
#define IDB_CANDY_CRUSH_6               746
#define IDB_CANDY_CRUSH_7               747
#define IDB_CANDY_CRUSH_8               748
#define IDB_CANDY_CRUSH_9               749
#define IDB_CANDY_CRUSH_10              750
#define IDB_CANDY_CRUSH_11              751
#define IDB_CANDY_CRUSH_12              752
#define IDB_CANDY_CRUSH_13              753
#define IDB_CANDY_CRUSH_14              754
#define IDB_CANDY_CRUSH_15              755
#define IDB_CANDY_CRUSH_16              756
#define IDB_CANDY_CRUSH_17              757
#define IDB_CANDY_CRUSH_18              758
#define IDB_CANDY_CRUSH_19              759
#define IDB_CANDY_CRUSH_20              760
#define IDB_CANDY_CRUSH_21              761
#define IDB_CANDY_CRUSH_22              762
#define IDB_CANDY_CRUSH_23              763
#define IDB2_0                          764
#define IDB2_1                          765
#define IDB2_2                          766
#define IDB2_3                          767
#define IDB2_4                          768
#define IDB2_5                          769
#define IDB2_6                          770
#define IDB2_7                          771
#define IDB2_8                          772
#define IDB2_9                          773
#define IDB_NEXTBTN_0                   774
#define IDB_NEXTBTN_1                   775
#define IDB_NEXTBTN_2                   776
#define IDB_NEXTBTN_3                   777
#define IDB_NEXTBTN_4                   778
#define IDB_NEXTBTN_5                   779
#define IDB_NEXTBTN_6                   780
#define IDB_NEXTBTN_7                   781
#define IDB_NEXTBTN_8                   782
#define IDB_NEXTBTN_9                   783
#define IDB_NEXTBTN_c                   784
#define IDB_RETRYBTN_0                  785
#define IDB_RETRYBTN_1                  786
#define IDB_RETRYBTN_2                  787
#define IDB_RETRYBTN_3                  788
#define IDB_RETRYBTN_4                  789
#define IDB_RETRYBTN_5                  790
#define IDB_RETRYBTN_6                  791
#define IDB_RETRYBTN_7                  792
#define IDB_RETRYBTN_8                  793
#define IDB_RETRYBTN_9                  794
#define IDB_RETRYBTN_c                  795
#define IDB3_0                          796
#define IDB3_1                          797
#define IDB3_2                          798
#define IDB3_3                          799
#define IDB3_4                          800
#define IDB3_5                          801
#define IDB3_6                          802
#define IDB3_7                          803
#define IDB3_8                          804
#define IDB3_9                          805
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
